---
title: "Progress Memo 1"
subtitle: |
  | Final Project 
  | Data Science 1 with R (STAT 301-1)
author: "Sana Nanlawala"
date: "October 29, 2023"

format:
  html:
    toc: true
    embed-resources: true
    
execute:
  echo: true
  warning: false

from: markdown+emoji 
---

::: {.callout-tip icon=false}

## Github Repo Link

[https://github.com/stat301-1-2023-fall/final-project-1-SanaNanlawala2026.git](https://github.com/stat301-1-2023-fall/final-project-1-SanaNanlawala2026.git)

:::


## Data source

This dataframe was sourced from Kaggle at: 
[https://www.kaggle.com/datasets/danofer/law-school-admissions-bar-passage/](https://www.kaggle.com/datasets/danofer/law-school-admissions-bar-passage/)

It was originally collected for a study called 'LSAC National Longitudinal Bar Passage Study' by Linda Wightman in 1998.

## Why this data TEST
I chose this data set because I am interested in applying to law school in the future, whether at the end of undergrad or a few laters after graduating. I think the law school application process is pretty complicated in comparison to general undergraduate applications, and want to see an exploration of the students who have applied in the past. While this data is not entirely representative of 2023 and law school applications today, it is interesting to see how the data was collected in the later 1900s with an emphasis on gender/race proportionality. 


## Data quality & complexity check
Below, I am reading in the dataset names bar_pass_prediction. There are 39 variables, of which 9 are categorical and the other 30 are numeric. This makes sense because a lot of these variables focus on test scores and dates, while the few categoric variables focus on identifying the student with their gender, race, etc. There are some missingness issues with students not providing specific data such as their gender, race, family income, etc.
```{r}
library(tidyverse)
bar_pass_prediction <- read_csv("data/bar_pass_prediction.csv")
bar_pass_prediction |> 
  slice_head(n = 5)
```

## Potential data issues

The data does require some cleaning because for example, the LSAT scores listed are raw scores, out of 50, while the general LSAT score is out of 160, so I would like to potentially find a way to convert it. Another thing is that the birth year for each student only shows the last two digits of the year, and while I personally know that all of these students were born in the 1900s, I want to convert the values to indicate that. Another thing is that there is repetition of race as a variable and I want to differentiate the purpose of each. Also, the age variable has values with a negative sign before it and the ages go as low as 3 (or rather, -3) which I want to potentially look more into and figure out what the actual age is and what these values represent. 

## Misc

I am hoping to also narrow down the list of columns to actual relevant information. For example there is a column named 'zfygpa' which is extremely confusing when there is already a column named gpa. 
